Alex Yastrebov
kate-sagittarius/frontend-team pull request #14
Opened 2019-09-09 17:30 UTC by Alexhawk13

created file

2019-09-10 14:06 UTC, kate-sagittarius requested changes
Please, check and correct the file and then we will merge

2019-09-10 14:06 UTC, kate-sagittarius commented on styles/Alex-Yastrebov.css
> +height:100%;
indents

2019-09-10 14:06 UTC, kate-sagittarius commented on styles/Alex-Yastrebov.css
> +  margin-top: 0px;
try avoiding pushing commenting code, it is not a very nice practice

2019-09-10 14:06 UTC, kate-sagittarius commented on team-members/Alex-Yastrebov.html
> +     <title></title>
please, add title

2019-09-10 14:06 UTC, kate-sagittarius commented on team-members/Alex-Yastrebov.html
> +  The size of our homes shapes so much of our lives.
indents

2019-09-10 17:30 UTC, Alexhawk13 commented on styles/Alex-Yastrebov.css
> +height:100%;
done? )

2019-09-10 17:30 UTC, OleksandrYastrebov commented on styles/Alex-Yastrebov.css
> +  margin-top: 0px;
done

2019-09-10 17:31 UTC, Alexhawk13 commented on team-members/Alex-Yastrebov.html
> +     <title></title>
done

2019-09-10 17:31 UTC, Alexhawk13 commented on styles/Alex-Yastrebov.css
> +height:100%;
Какие отступы?

2019-09-10 17:32 UTC, Alexhawk13 commented on team-members/Alex-Yastrebov.html
> +  The size of our homes shapes so much of our lives.
done

2019-09-10 20:01 UTC, kate-sagittarius commented on styles/Alex-Yastrebov.css
> +height:100%;
css should look like this:
```
body, html {
  height: 100%;
}
````

2019-09-11 05:11 UTC, Alexhawk13 commented on styles/Alex-Yastrebov.css
> +height:100%;
done

2019-09-11 14:39 UTC, merged